### ISSUE TITLE
Miniget error 403

### ISSUE THREAD

**Issue by LeoTheMoldyLemon** [tobilg/youtube-mp3-downloader#89]
Trying to download a video, 403 error pops up. Maybe i am dumb? Maybe youtube uped security? Idk and i'm sorry if it's the former.

![image](https://user-images.githubusercontent.com/62692318/133907093-bbb51e4d-b896-4694-b24d-df030df4d5b9.png)
![image](https://user-images.githubusercontent.com/62692318/133907105-959d3b27-f540-4c4b-b597-a9828d399609.png)

Cropped the second image so you can't see my token.

**Comment by ytb2mp3** [comment]
I'm releasing `v0.7.8` in a few minutes with updated dependencies, please try again then.

**Comment by mepc36** [comment]
I'm still getting this `403` error from `Miniget`, any update @ytb2mp3 ? Just wondering, great package otherwise 👍  thanks for all your hard work on it!

**Comment by ytb2mp3** [comment]
Sure you have the latest version installed @mepc36? If so, which videoId are you trying to download?

**Comment by mepc36** [comment]
> Sure you have the latest version installed @mepc36? If so, which videoId are you trying to download?

Hey ytb2mp3, yes I think I have the latest version (it's 0.7.8, right?)

I do not have the videoId that it failed on. I did just add a log to my prod env that will capture the `videoId`, since it wasn't doing so before. I think I got the `403` when I tried to fetch id `b7dNw74-LTE`, but I just tried to reproduce the bug when fetching that specific video and couldn't. Sorry for the lack of helpful info! I'll be sure to check back in if/when the `403` happens again. 

So far my gut is that the problem doesn't have to do with the specific video I'm fetching, but, instead, with the number of requests I'm doing per minute.

Thanks man!

**Comment by mepc36** [comment]
Just got a hit, here's the log; the troublesome ID is `4Q-6whdEVpM`:

```
$$$ youtubeVideoId for Juice WRLD - "All Out": 4Q-6whdEVpM
MinigetError: Status code: 403
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12) {
  statusCode: 403
}
```

**Comment by mepc36** [comment]
Fetching that ID again does not reproduce error:

```
$$$ FETCHING media for Juice WRLD - "All Out"
$$$ youtubeVideoId for Juice WRLD - "All Out": 4Q-6whdEVpM
Juice WRLD - "All Out": {"videoId":"4Q-6whdEVpM","progress":{"percentage":9.363485769196542,"transferred":344064,"length":3674529,"remaining":3330465,"eta":53,"runtime":5,"delta":344064,"speed":62557.09090909091}}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Juice WRLD - "All Out": {"videoId":"4Q-6whdEVpM","progress":{"percentage":18.726971538393084,"transferred":688128,"length":3674529,"remaining":2986401,"eta":47,"runtime":10,"delta":344064,"speed":64011.90697674418}}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Juice WRLD - "All Out": {"videoId":"4Q-6whdEVpM","progress":{"percentage":28.090457307589627,"transferred":1032192,"length":3674529,"remaining":2642337,"eta":41,"runtime":15,"delta":344064,"speed":64512}}
~~~
```

**Comment by ziad67-bytes** [comment]
Hello I have the same error because i download a youtube video in a loop. Here is my code : 
 
```
const YD = new youtubeDownloader({
    "ffmpegPath" : "C:/ffmpeg-4.4.1-essentials_build/ffmpeg-4.4.1-essentials_build/bin/ffmpeg.exe",
    "outputPath" : "./album/17",
    "youtubeVideoQuality" : "highestaudio",
})

for (const element in data) {
    YD.download(data[element],element+".mp3")
}
```
In data there is 10 element. Have you a solution, please help me

**Comment by mepc36** [comment]
@ziad67-bytes No solution yet, but I do know that the problem is probably not with `youtube-mp3-downloader` package. Checking out the issues for the core functionality of which `youtube-mp3-downloader` is mainly a wrapper, `ytdl-core`, they have the same issues over there: 

https://github.com/fent/node-ytdl-core/issues/854

No one mentions a solution over there either. For now, I am just wrapping the invocation and re-trying 3 times before it fails...not the prettiest, but every time it's been retried (with a 3 second delay in-between, in order to avoid the too-many-requests error that is probably causing this `403` error) it's worked.

**Comment by ziad67-bytes** [comment]
I try this but it doesn't work : 
function pausecomp(millis)
```
{
    var date = new Date();
    var curDate = null;
    do { curDate = new Date(); }
    while(curDate-date < millis);
}

for (const element in data) {
    try {
        YD.download(data[element],element+".mp3")
    }catch{
        pausecomp(3000);
        YD.download(data[element],element+".mp3")
    }
}
```
I don't know how to re-trying 3 times before it fails how you do this ?

**Comment by ytb2mp3** [comment]
The `403` status code means forbidden, and I assume it's just rate limiting on YouTube's side as it was already mentioned. This isn't something we can influence with this library. You need to make sure that you don't send too many requests in a row and/or at once.

I'll close this ticket.

**Comment by mepc36** [comment]
I agree with @ytb2mp3 , this error is not this package's problem.

@ziad67-bytes, this is my relevant code:

```
const downloadYoutubeAudio = (youtubeId, artist, title, outputMp3Name) => {
  const YD = new YoutubeMp3Downloader({
    "ffmpegPath": `/usr/local/bin/ffmpeg`,
    "outputPath": `${__dirname}/output`,
    "youtubeVideoQuality": "highestaudio",
    "queueParallelism": 2,
    "progressTimeout": 5000,
    "allowWebm": false
  });

  YD.download(youtubeId, outputMp3Name);

  return new Promise((resolve, reject) => {
    YD.on("finished", (err, data) => {
      console.log(JSON.stringify(data));
      resolve('downloaded!')
    });

    YD.on("error", (error) => {
      console.log(error);
      reject(error)
    });

    YD.on("progress", (progress) => {
      console.log(`${artist} - "${title}": ${JSON.stringify(progress)}`);
      console.log('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    });
  })
}

async function wait(delay) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, delay);
  });
}

function makeRetryable(fn, attemptCount = 3, delay = 3000) {
  return async function retryable(...args) {
    for (let attempt = 1; attempt < attemptCount; attempt++) {
      try {
        const result = await fn(...args);
        return result;
      } catch (err) {
        if (attempt < attemptCount) {
          if (delay > 0) {
            await wait(delay);
          }
        } else {
          throw err;
        }
      }
    }
  };
}

const retryableDownloadYoutubeAudio = makeRetryable(downloadYoutubeAudio)
```

I have a utility function that makes anything retryable a configurable number of times, and then another utility func named `wait` that will wait to retry a function. By default `makeRetryable` will retry something 3 times., before throwing an error for real. Hope this helps!

**Comment by ziad67-bytes** [comment]
@mepc36  Thank you very much, it helped me a lot but I don't understand why you create the variable `retryableDownloadYoutubeAudio` and why not just print` makeRetryable(downloadYoutubeAudio(youtubeId, artist, title, outputMp3Name)` ?

**Comment by ziad67-bytes** [comment]
@mepc36 it still doesn't work for me :( but I'll try to find another way
