### ISSUE TITLE
Taking too much time to download the song

### ISSUE THREAD

**Issue by vikram-sapate** [tobilg/youtube-mp3-downloader#94]
It was taking just few secs to download the song before,
but now a days it is taking **60 secs** for just **2 minute video.**

Internet speed is not an issue as I'm using aws ec2 instance.
Please let me know how can I fix this.

**Comment by MalekYagoub** [comment]
I have the same issue, it takes minutes to download a song now

**Comment by ytb2mp3** [comment]
I'd guess you're getting rate limited and/or throttled. There's not really anything I can do to change this from the library's perspective.
